# Generated by Django 5.2.7 on 2025-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_blealert_cloudalert"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blealert",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="cloudalert",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="blealert",
            name="broadcast_duration",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="blealert",
            name="location_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blealert",
            name="severity",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blealert",
            name="status",
            field=models.CharField(
                choices=[
                    ("broadcast", "Broadcast"),
                    ("received", "Received"),
                    ("expired", "Expired"),
                ],
                default="broadcast",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="cloudalert",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cloudalert",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cloudalert",
            name="is_emergency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cloudalert",
            name="title",
            field=models.CharField(default="Emergency Alert", max_length=255),
        ),
        migrations.AlterField(
            model_name="cloudalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("read", "Read"),
                ],
                default="sent",
                max_length=50,
            ),
        ),
    ]
